# This is a basic workflow to help you get started with Actions

name: CDelivery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Clone the repo
        run: git clone https://github.com/Luzifer/ots.git

      - name: build a Image
        working-directory: ots
        run: |
          git   checkout 3.0.0
          docker build -t us-central1-docker.pkg.dev/light-processor-377018/team4/ots:latest  .

      - name: Authenticate  to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '{{ secrets.SERVICE_ACCOUNT }}'


      - name: Autheticate to Arifact Registry
        run: |
          gcloud auth configure-docker   us-central1-docker.pkg.dev
        
      - name: pushe the image to Artifact 
        run: docker push us-central1-docker.pkg.dev/light-processor-377018/team4/ots:3.0.0   

    
      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
