env:
  repo: https://github.com/Luzifer/ots.git  #https://github.com/Aselya2507/project-testing.git
  app_version: 5.0.0
  region: us-central1
  project_id: ${{ secrets.PROJECT_ID }}
  app_name: ots
  tag_new_version: ${GITHUB_SHA}
  artifact_repository: team4
  enable_sonar:    "true"
  sonar_organization: ${{ secrets.SONAR_ORGANIZATION }}
  sonar_projectKey: $ {{ secrets.SONAR_PROJECT_KEY }}
  sonar_login: ${{ secrets.SONAR_TOKEN }}
name: CDelivery
on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone a Repository
        run: |
          git clone ${{ env.repo }}
         
      - name: Setup sonarqube
        if: ${{env.enable_sonar == 'true'}}
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        if: ${{env.enable_sonar == 'true'}}
        run: sonar-scanner
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}                              
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}                         
            -Dsonar.login=${{ secrets.SONAR_TOKEN  }}                                   
            -Dsonar.host.url=https://sonarcloud.io

      - name: Build the image
        working-directory: ${{ env.app_name }}
        run: 
          docker build -t ${{ env.region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.artifact_repository }}/${{ env.app_name }}:${{ env.tag_new_version }} .

      - name: Authenticate to Registry 
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'   

      - name: Authenticate to Repository
        run: |
          gcloud auth configure-docker    us-central1-docker.pkg.dev 

      - name: push
        run: docker push ${{ env.region }}-docker.pkg.dev/${{ env.project_id }}/${{ env.artifact_repository }}/${{ env.app_name }}:${{ env.tag_new_version }} 

      